rootProject.name = 'payment-processor-platform'

include(
    'gateway-service',
    'authentication-service',
    'user-service',
    'merchant-service',
    'payment-service',
    'fraud-service',
    'ledger-service',
    'settlement-service',
    'clearing-service',
    'reconciliation-service',
    'dispute-service',
    'notification-service',
    'audit-service',
    'tokenization-service',
    'limit-service',
    'authorization-service',
    'reporting-service'
)
