spring:
  application:
    name: limit-service
  datasource:
    url: jdbc:postgresql://db-dev.internal:5432/limit_dev
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    baseline-on-migrate: true
  data:
    redis:
      host: redis-dev.internal
      port: 6379
      password: ${REDIS_PASSWORD}
      timeout: 2000ms

server:
  port: 8085

eureka:
  client:
    service-url:
      defaultZone: http://eureka-dev.internal:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: limit-service-dev

limit:
  daily-transaction-limit: 10000.00
  monthly-transaction-limit: 100000.00
  per-transaction-limit: 50000.00
  velocity-window-minutes: 60
  velocity-max-transactions: 20

logging:
  level:
    root: WARN
    com.paymentprocessor: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
