-- ============================================================================
-- Ledger Service - initial schema (PostgreSQL)
-- Immutable, append-only double-entry ledger.
-- ============================================================================

-- Reference: supported currencies -------------------------------------------
CREATE TABLE currencies (
    code       VARCHAR(3)  PRIMARY KEY,
    exponent   SMALLINT    NOT NULL,
    name       VARCHAR(64)
);

-- Reference: account types (classification + normal balance) ------------------
CREATE TABLE account_types (
    code            VARCHAR(16)  PRIMARY KEY,
    classification  VARCHAR(16)  NOT NULL,   -- ASSET | LIABILITY | EQUITY | REVENUE | EXPENSE
    normal_balance  VARCHAR(8)   NOT NULL,   -- DEBIT | CREDIT
    description     VARCHAR(255)
);

-- Chart of accounts ----------------------------------------------------------
CREATE TABLE accounts (
    id                 VARCHAR(64)  PRIMARY KEY,
    account_code       VARCHAR(32)  NOT NULL,
    name               VARCHAR(255) NOT NULL,
    owner_type         VARCHAR(32),
    owner_id           VARCHAR(64),
    type_code          VARCHAR(16)  NOT NULL REFERENCES account_types(code),
    currency           VARCHAR(3)   NOT NULL REFERENCES currencies(code),
    parent_account_id  VARCHAR(64),
    status             VARCHAR(16)  NOT NULL DEFAULT 'ACTIVE',
    created_at         TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uq_accounts_code UNIQUE (account_code)
);
CREATE INDEX idx_accounts_owner ON accounts (owner_type, owner_id);
CREATE INDEX idx_accounts_type  ON accounts (type_code);

-- Accounting periods ---------------------------------------------------------
CREATE TABLE accounting_periods (
    id           VARCHAR(64)  PRIMARY KEY,
    code         VARCHAR(32)  NOT NULL,
    period_type  VARCHAR(16)  NOT NULL,   -- DAILY | WEEKLY | MONTHLY | QUARTERLY | YEARLY
    start_date   DATE         NOT NULL,
    end_date     DATE         NOT NULL,
    state        VARCHAR(16)  NOT NULL DEFAULT 'OPEN',  -- OPEN | CLOSING | CLOSED | LOCKED
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    closed_at    TIMESTAMPTZ,
    CONSTRAINT uq_period_code UNIQUE (code)
);
CREATE INDEX idx_period_dates ON accounting_periods (start_date, end_date);

-- Journals (the atomic, balanced financial event) ----------------------------
CREATE TABLE journals (
    id                     VARCHAR(64)  PRIMARY KEY,
    event_type             VARCHAR(64),
    external_ref           VARCHAR(128),
    idempotency_key        VARCHAR(128),
    description            VARCHAR(512),
    metadata               TEXT,
    status                 VARCHAR(16)  NOT NULL DEFAULT 'POSTED',  -- POSTED | REVERSED
    reverses_journal_id    VARCHAR(64),
    reversed_by_journal_id VARCHAR(64),
    reversal_reason        VARCHAR(32),
    period_id              VARCHAR(64),
    effective_at           TIMESTAMPTZ  NOT NULL,
    posted_at              TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by             VARCHAR(64),
    CONSTRAINT uq_journal_idempotency UNIQUE (idempotency_key)
);
CREATE INDEX idx_journals_external_ref ON journals (external_ref);
CREATE INDEX idx_journals_event_type   ON journals (event_type);
CREATE INDEX idx_journals_reverses     ON journals (reverses_journal_id);
CREATE INDEX idx_journals_posted_at    ON journals (posted_at);

-- Entries (individual debit/credit lines; immutable) -------------------------
CREATE TABLE entries (
    id            BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    journal_id    VARCHAR(64)  NOT NULL REFERENCES journals(id),
    line_number   INT          NOT NULL,
    account_id    VARCHAR(64)  NOT NULL REFERENCES accounts(id),
    direction     VARCHAR(8)   NOT NULL,   -- DEBIT | CREDIT
    amount_minor  BIGINT       NOT NULL,
    currency      VARCHAR(3)   NOT NULL,
    description   VARCHAR(512),
    effective_at  TIMESTAMPTZ  NOT NULL,
    CONSTRAINT chk_entry_amount_positive CHECK (amount_minor > 0)
);
CREATE INDEX idx_entries_journal ON entries (journal_id);
CREATE INDEX idx_entries_account ON entries (account_id, id);

-- Real-time account balances (denormalised, optimistic-locked) ---------------
CREATE TABLE account_balances (
    account_id        VARCHAR(64)  PRIMARY KEY REFERENCES accounts(id),
    currency          VARCHAR(3)   NOT NULL,
    posted_minor      BIGINT       NOT NULL DEFAULT 0,
    pending_minor     BIGINT       NOT NULL DEFAULT 0,
    held_minor        BIGINT       NOT NULL DEFAULT 0,
    available_minor   BIGINT       NOT NULL DEFAULT 0,
    entry_high_water  BIGINT       NOT NULL DEFAULT 0,
    version           INT          NOT NULL DEFAULT 0,
    updated_at        TIMESTAMPTZ  NOT NULL DEFAULT now()
);

-- Optional sharded balance accumulators (hot-account write contention relief) -
CREATE TABLE balance_shards (
    account_id    VARCHAR(64)  NOT NULL REFERENCES accounts(id),
    shard         SMALLINT     NOT NULL,
    posted_minor  BIGINT       NOT NULL DEFAULT 0,
    PRIMARY KEY (account_id, shard)
);

-- Holds / reservations against available balance -----------------------------
CREATE TABLE holds (
    id            VARCHAR(64)  PRIMARY KEY,
    account_id    VARCHAR(64)  NOT NULL REFERENCES accounts(id),
    amount_minor  BIGINT       NOT NULL,
    currency      VARCHAR(3)   NOT NULL,
    reason        VARCHAR(64),
    status        VARCHAR(16)  NOT NULL DEFAULT 'ACTIVE',  -- ACTIVE | RELEASED | EXPIRED | CAPTURED
    external_ref  VARCHAR(128),
    expires_at    TIMESTAMPTZ,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    released_at   TIMESTAMPTZ,
    CONSTRAINT chk_hold_amount_positive CHECK (amount_minor > 0)
);
CREATE INDEX idx_holds_account ON holds (account_id, status);

-- Point-in-time balance snapshots (immutable) --------------------------------
CREATE TABLE balance_snapshots (
    account_id        VARCHAR(64)  NOT NULL REFERENCES accounts(id),
    as_of_date        DATE         NOT NULL,
    snapshot_type     VARCHAR(16)  NOT NULL DEFAULT 'EOD',
    opening_minor     BIGINT       NOT NULL DEFAULT 0,
    debit_minor       BIGINT       NOT NULL DEFAULT 0,
    credit_minor      BIGINT       NOT NULL DEFAULT 0,
    posted_minor      BIGINT       NOT NULL DEFAULT 0,   -- closing balance (normal-side signed)
    entry_count       BIGINT       NOT NULL DEFAULT 0,
    entry_high_water  BIGINT       NOT NULL DEFAULT 0,
    last_entry_at     TIMESTAMPTZ,
    created_at        TIMESTAMPTZ  NOT NULL DEFAULT now(),
    PRIMARY KEY (account_id, as_of_date)
);

-- Transactional outbox for reliable event publishing -------------------------
CREATE TABLE outbox_events (
    id              VARCHAR(64)  PRIMARY KEY,
    aggregate_type  VARCHAR(32)  NOT NULL,
    aggregate_id    VARCHAR(64)  NOT NULL,
    event_type      VARCHAR(48)  NOT NULL,
    payload         TEXT         NOT NULL,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    published       BOOLEAN      NOT NULL DEFAULT FALSE,
    published_at    TIMESTAMPTZ
);
CREATE INDEX idx_outbox_unpublished ON outbox_events (published, created_at);
